### ISSUE TITLE
subsetting wikipedia by categorytree

### ISSUE THREAD

**Issue by keighrim** [brandeis-llc/dtriac-wikification#6]
As a subtask of #5, I want to have a software that given a category name in the wiki category tree, filters documents from wikidump (either [the XML dump](https://dumps.wikimedia.org/backup-index.html) or [cirrus dump](https://dumps.wikimedia.org/other/cirrussearch/), but preferably cirrus dump) that fall onto the subcategories of the input category.

**Comment by keighrim** [comment]
Initial implementation is pushed and available via #7. I also pushed [an example subset](https://github.com/brandeis-llc/dtriac-wikification/blob/946085d5e70dfaf2a92229c4587308a3416a64c9/subset/Nuclear_weapons.txt) I obtained by using [`Nuclear_weapons`](https://en.wikipedia.org/wiki/Special:CategoryTree?target=Category%3ANuclear+weapons&mode=categories&namespaces=&title=Special%3ACategoryTree) as a top category, which gave me 12,446 articles. I'm also running it with [`Nuclear_technology`](https://en.wikipedia.org/wiki/Special:CategoryTree?target=Category%3ANuclear+technology&mode=categories&namespaces=&title=Special%3ACategoryTree) (supersets `Nuclear_weapons`), and it's taking a lot more time.

**Comment by keighrim** [comment]
09452ab51210677d4df936db0909ebb3fe635d84 adds another subset, namely from `Nuclear_technology` category, with 55214 articles. (It took ~10 minutes). I also started to run it with `Nuclear_physics` (supersets `Nuclear_technology`, and includes god knows how many radioisotopes pages), and it still running for more that 11 hrs now.

**Comment by jxtu** [comment]
Do we have the 55214 wiki articles from `Nuclear_technology` somewhere in the server? I would like to play with the embeddings. (I already trained the dtra word embeddings, it looks like we can get something meaning from the content)

**Comment by keighrim** [comment]
I used a recent dump (12/23/2019) and `grep` those 55k titles from the dump and indexed into `tarski` ES under index name `enwiki-nuclear_technology`. (can be accessed via kibana at [here](http://tarski.cs-i.brandeis.edu:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'39dddef0-3020-11ea-97de-75cd4e0d8ddd',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))).
 However, for some reason, my code doesn't get all the articles and ends up with only 34,443 documents indexed there. I'm investigating this issue right now. In the meantime, you should be able to get all the text from the index by performing ES search. (see [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-scroll) for performing a large retrieval.) The text is encoded in the `.hits.hits[]._source.text` field in the search results. (`[]` means that field is a list)

**Comment by keighrim** [comment]
The reason why only \~60% of the articles from the `Nuclear_technology` slice seems to be because of existence of duplicate titles (tagged with multiple categories of interest) and page "redirects" (works as aliases for a page in essence). I fixed my code and started re-index as `enwiki-nuke_tech` (note the difference in the name), and expecting \~35k articles to be indexed in next couple of hrs.

**Comment by keighrim** [comment]
done via #7. `enwiki-nuke_tech` index on the `tarski` ES contains \~35k documents from `Nuclear technology` articles.
